language: android

android:

    update_sdk: true
    
    components:
    
        - tools
        - platform-tools
        - build-tools-25.0.2
        - android-25
        - extra-android-m2repository
        - sys-img-armeabi-v7a-android-21
        - sys-img-armeabi-v7a-android-19
        - sys-img-armeabi-v7a-android-tv-21
                
    licenses:
        - android-sdk-preview-license-52d11cd2
        - android-sdk-license-.+
        - google-gdk-license-.+     
        
        
env:
  matrix:
     - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a   
     - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a    
        
jdk:
  - oraclejdk8


install:
- echo yes | sdkmanager extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2
- echo yes | sdkmanager extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2
  
before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &  
  
script:
   - ./gradlew build connectedCheck --stacktrace     