language: android

android:
    components:
    
        - tools
        - platform-tools
        - tools
        - build-tools-25.0.2
        - android-25
        - extra-android-m2repository
        - sys-img-armeabi-v7a-android-25
        - sys-img-armeabi-v7a-android-tv-25
                
    licenses:
        - android-sdk-preview-license-52d11cd2
        - android-sdk-license-.+
        - google-gdk-license-.+     
        
        
env:
  matrix:
     - ANDROID_TARGET=android-25  ANDROID_ABI=armeabi-v7a       
        
jdk:
  - oraclejdk8
  
  
before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &  
  
script:
   - ./gradlew build connectedCheck     