language: android

android:

    components:
    
        - build-tools-25.0.2
        - android-25
        - tools
        - extra-android-m2repository
        - platform-tools
        - sys-img-armeabi-v7a-android-19
        - sys-img-armeabi-v7a-android-22
        
        