language: android

android:
    components:
    
        - tools
        - tools
        - platform-tools
        - build-tools-25.0.2
        - android-21
        - extra-android-m2repository
        - sys-img-armeabi-v7a-android-21
        - sys-img-armeabi-v7a-android-tv-21
        - extra-android-support
                
    licenses:
        - android-sdk-preview-license-52d11cd2
        - android-sdk-license-.+
        - google-gdk-license-.+       
        
jdk:
  - oraclejdk8
  
  
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &  
  
script:
   - ./gradlew build connectedCheck     